APP_ENV=local
APP_KEY=base64:A0Cv+VgIYL5PD1hBkzDL7W++jCn1POKQu6E6GBLPOGo=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://videoto.ir

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=admin_videoto
DB_USERNAME=admin_videoto
DB_PASSWORD=e6wRm5NXl

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=tls

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=

GOOGLE_CLIENT_ID=833817446635-c4np8rcbjkm9grm51enqrlmbm6l59pbt.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=zQ4B_vCzpWJUuvfZ4HUYpX-4
GOOGLE_REDIRECT_URL=http://videoto.ir/user/google/login
